// IRT-Calibrated Item Bank for MBTI Assessment
// 2PL model parameters based on psychometric research

import type { PsychometricItem } from '@/types/psychometric'

/**
 * Seed data: IRT-calibrated items for MBTI dimensions
 * Each dimension has 20+ items with varying difficulty and discrimination
 *
 * IRT Parameters:
 * - discrimination (a): 0.8-2.0 (higher = more informative)
 * - difficulty (b): -2.0 to +2.0 (negative = easier to endorse first pole)
 * - guessing (c): 0 for forced-choice items
 */

// ===========================================
// E/I DIMENSION (Extraversion/Introversion)
// ===========================================

export const EI_ITEMS: Omit<PsychometricItem, 'id'>[] = [
  {
    itemCode: 'EI-001',
    dimension: 'EI',
    questionTextRu: 'В свободное время я предпочитаю...',
    questionTextEn: 'In my free time, I prefer...',
    optionATextRu: 'Встречаться с друзьями, ходить на мероприятия',
    optionATextEn: 'Meeting friends, attending events',
    optionBTextRu: 'Проводить время в одиночестве или с близкими',
    optionBTextEn: 'Spending time alone or with close ones',
    irt: { discrimination: 1.5, difficulty: 0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-002',
    dimension: 'EI',
    questionTextRu: 'После долгого дня общения я чувствую себя...',
    questionTextEn: 'After a long day of socializing, I feel...',
    optionATextRu: 'Воодушевлённым и энергичным',
    optionATextEn: 'Energized and enthusiastic',
    optionBTextRu: 'Уставшим и нуждающимся в отдыхе',
    optionBTextEn: 'Tired and needing rest',
    irt: { discrimination: 1.8, difficulty: -0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-003',
    dimension: 'EI',
    questionTextRu: 'Я лучше думаю когда...',
    questionTextEn: 'I think best when...',
    optionATextRu: 'Обсуждаю идеи с другими',
    optionATextEn: 'Discussing ideas with others',
    optionBTextRu: 'Размышляю в тишине',
    optionBTextEn: 'Reflecting in silence',
    irt: { discrimination: 1.6, difficulty: 0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-004',
    dimension: 'EI',
    questionTextRu: 'На вечеринках я обычно...',
    questionTextEn: 'At parties, I usually...',
    optionATextRu: 'Общаюсь со многими людьми',
    optionATextEn: 'Talk to many people',
    optionBTextRu: 'Разговариваю с несколькими близкими',
    optionBTextEn: 'Talk to a few close people',
    irt: { discrimination: 1.4, difficulty: -0.8, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-005',
    dimension: 'EI',
    questionTextRu: 'Я восстанавливаю энергию через...',
    questionTextEn: 'I recharge my energy through...',
    optionATextRu: 'Активность и взаимодействие с людьми',
    optionATextEn: 'Activity and interaction with people',
    optionBTextRu: 'Уединение и тихое времяпрепровождение',
    optionBTextEn: 'Solitude and quiet time',
    irt: { discrimination: 2.0, difficulty: 0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-006',
    dimension: 'EI',
    questionTextRu: 'При знакомстве я...',
    questionTextEn: 'When meeting new people, I...',
    optionATextRu: 'Легко начинаю разговор',
    optionATextEn: 'Easily start a conversation',
    optionBTextRu: 'Жду, пока другие начнут',
    optionBTextEn: 'Wait for others to initiate',
    irt: { discrimination: 1.3, difficulty: -1.0, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-007',
    dimension: 'EI',
    questionTextRu: 'Я предпочитаю работать...',
    questionTextEn: 'I prefer to work...',
    optionATextRu: 'В команде, с другими людьми',
    optionATextEn: 'In a team, with other people',
    optionBTextRu: 'Самостоятельно, в своём темпе',
    optionBTextEn: 'Independently, at my own pace',
    irt: { discrimination: 1.2, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-008',
    dimension: 'EI',
    questionTextRu: 'Мой круг общения...',
    questionTextEn: 'My social circle...',
    optionATextRu: 'Широкий, много знакомых',
    optionATextEn: 'Wide, many acquaintances',
    optionBTextRu: 'Узкий, несколько близких друзей',
    optionBTextEn: 'Narrow, a few close friends',
    irt: { discrimination: 1.7, difficulty: -0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-009',
    dimension: 'EI',
    questionTextRu: 'В разговоре я склонен...',
    questionTextEn: 'In conversation, I tend to...',
    optionATextRu: 'Думать вслух, высказывать мысли сразу',
    optionATextEn: 'Think out loud, share thoughts immediately',
    optionBTextRu: 'Сначала обдумывать, потом говорить',
    optionBTextEn: 'Think first, then speak',
    irt: { discrimination: 1.5, difficulty: 0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-010',
    dimension: 'EI',
    questionTextRu: 'Мне комфортнее всего...',
    questionTextEn: 'I feel most comfortable...',
    optionATextRu: 'В центре внимания',
    optionATextEn: 'In the spotlight',
    optionBTextRu: 'Оставаясь в тени',
    optionBTextEn: 'Staying in the background',
    irt: { discrimination: 1.4, difficulty: -1.2, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-011',
    dimension: 'EI',
    questionTextRu: 'Я получаю новые идеи...',
    questionTextEn: 'I get new ideas...',
    optionATextRu: 'Обсуждая с другими',
    optionATextEn: 'By discussing with others',
    optionBTextRu: 'В уединении и размышлениях',
    optionBTextEn: 'In solitude and reflection',
    irt: { discrimination: 1.6, difficulty: 0.8, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-012',
    dimension: 'EI',
    questionTextRu: 'Когда телефон звонит, я...',
    questionTextEn: 'When the phone rings, I...',
    optionATextRu: 'С радостью отвечаю',
    optionATextEn: 'Happily answer',
    optionBTextRu: 'Иногда игнорирую звонок',
    optionBTextEn: 'Sometimes ignore the call',
    irt: { discrimination: 1.1, difficulty: 0.4, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-013',
    dimension: 'EI',
    questionTextRu: 'После работы я предпочитаю...',
    questionTextEn: 'After work, I prefer to...',
    optionATextRu: 'Встретиться с коллегами или друзьями',
    optionATextEn: 'Meet with colleagues or friends',
    optionBTextRu: 'Побыть дома в тишине',
    optionBTextEn: 'Stay home in quiet',
    irt: { discrimination: 1.7, difficulty: -0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-014',
    dimension: 'EI',
    questionTextRu: 'В группе я обычно...',
    questionTextEn: 'In a group, I usually...',
    optionATextRu: 'Активно участвую в обсуждении',
    optionATextEn: 'Actively participate in discussion',
    optionBTextRu: 'Больше слушаю и наблюдаю',
    optionBTextEn: 'Listen and observe more',
    irt: { discrimination: 1.5, difficulty: -0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-015',
    dimension: 'EI',
    questionTextRu: 'Мне нравится...',
    questionTextEn: 'I enjoy...',
    optionATextRu: 'Шумные, оживлённые места',
    optionATextEn: 'Noisy, lively places',
    optionBTextRu: 'Тихие, спокойные места',
    optionBTextEn: 'Quiet, peaceful places',
    irt: { discrimination: 1.3, difficulty: 0.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-016',
    dimension: 'EI',
    questionTextRu: 'Я чувствую себя более живым когда...',
    questionTextEn: 'I feel more alive when...',
    optionATextRu: 'Вокруг много людей и активности',
    optionATextEn: 'Surrounded by people and activity',
    optionBTextRu: 'У меня есть время для себя',
    optionBTextEn: 'I have time for myself',
    irt: { discrimination: 1.9, difficulty: 0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-017',
    dimension: 'EI',
    questionTextRu: 'На совещании я...',
    questionTextEn: 'In meetings, I...',
    optionATextRu: 'Часто высказываю свои мысли',
    optionATextEn: 'Often share my thoughts',
    optionBTextRu: 'Высказываюсь когда это необходимо',
    optionBTextEn: 'Speak when necessary',
    irt: { discrimination: 1.4, difficulty: 0.7, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-018',
    dimension: 'EI',
    questionTextRu: 'Выходные я предпочитаю проводить...',
    questionTextEn: 'On weekends, I prefer to spend time...',
    optionATextRu: 'С людьми, на мероприятиях',
    optionATextEn: 'With people, at events',
    optionBTextRu: 'Дома, занимаясь своими делами',
    optionBTextEn: 'At home, doing my own things',
    irt: { discrimination: 1.6, difficulty: -0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-019',
    dimension: 'EI',
    questionTextRu: 'Я принимаю решения лучше всего...',
    questionTextEn: 'I make decisions best...',
    optionATextRu: 'Обсуждая варианты с другими',
    optionATextEn: 'Discussing options with others',
    optionBTextRu: 'Обдумывая их самостоятельно',
    optionBTextEn: 'Thinking them through alone',
    irt: { discrimination: 1.5, difficulty: 0.9, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'EI-020',
    dimension: 'EI',
    questionTextRu: 'Мне больше нравится...',
    questionTextEn: 'I prefer more...',
    optionATextRu: 'Разнообразие и внешние стимулы',
    optionATextEn: 'Variety and external stimuli',
    optionBTextRu: 'Стабильность и внутренний мир',
    optionBTextEn: 'Stability and inner world',
    irt: { discrimination: 1.7, difficulty: 1.0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
]

// ===========================================
// S/N DIMENSION (Sensing/Intuition)
// ===========================================

export const SN_ITEMS: Omit<PsychometricItem, 'id'>[] = [
  {
    itemCode: 'SN-001',
    dimension: 'SN',
    questionTextRu: 'Я больше доверяю...',
    questionTextEn: 'I trust more...',
    optionATextRu: 'Фактам и опыту',
    optionATextEn: 'Facts and experience',
    optionBTextRu: 'Интуиции и предчувствиям',
    optionBTextEn: 'Intuition and hunches',
    irt: { discrimination: 1.8, difficulty: 0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-002',
    dimension: 'SN',
    questionTextRu: 'При чтении я обращаю внимание на...',
    questionTextEn: 'When reading, I pay attention to...',
    optionATextRu: 'Буквальное значение текста',
    optionATextEn: 'Literal meaning of the text',
    optionBTextRu: 'Скрытый смысл и подтекст',
    optionBTextEn: 'Hidden meaning and subtext',
    irt: { discrimination: 1.6, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-003',
    dimension: 'SN',
    questionTextRu: 'Я предпочитаю...',
    questionTextEn: 'I prefer...',
    optionATextRu: 'Проверенные методы',
    optionATextEn: 'Proven methods',
    optionBTextRu: 'Новые возможности',
    optionBTextEn: 'New possibilities',
    irt: { discrimination: 1.7, difficulty: -0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-004',
    dimension: 'SN',
    questionTextRu: 'Меня больше интересует...',
    questionTextEn: 'I am more interested in...',
    optionATextRu: 'Реальность и настоящее',
    optionATextEn: 'Reality and the present',
    optionBTextRu: 'Возможности и будущее',
    optionBTextEn: 'Possibilities and the future',
    irt: { discrimination: 2.0, difficulty: 0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-005',
    dimension: 'SN',
    questionTextRu: 'При решении задач я полагаюсь на...',
    questionTextEn: 'When solving problems, I rely on...',
    optionATextRu: 'Практический опыт',
    optionATextEn: 'Practical experience',
    optionBTextRu: 'Воображение и инсайты',
    optionBTextEn: 'Imagination and insights',
    irt: { discrimination: 1.5, difficulty: 0.7, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-006',
    dimension: 'SN',
    questionTextRu: 'Я чаще замечаю...',
    questionTextEn: 'I notice more often...',
    optionATextRu: 'Детали и конкретику',
    optionATextEn: 'Details and specifics',
    optionBTextRu: 'Общую картину и паттерны',
    optionBTextEn: 'Big picture and patterns',
    irt: { discrimination: 1.9, difficulty: -0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-007',
    dimension: 'SN',
    questionTextRu: 'Мне интереснее...',
    questionTextEn: 'I find more interesting...',
    optionATextRu: 'То, что есть',
    optionATextEn: 'What is',
    optionBTextRu: 'То, что могло бы быть',
    optionBTextEn: 'What could be',
    irt: { discrimination: 1.4, difficulty: 0.8, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-008',
    dimension: 'SN',
    questionTextRu: 'Я предпочитаю работать с...',
    questionTextEn: 'I prefer to work with...',
    optionATextRu: 'Конкретными данными',
    optionATextEn: 'Concrete data',
    optionBTextRu: 'Абстрактными концепциями',
    optionBTextEn: 'Abstract concepts',
    irt: { discrimination: 1.6, difficulty: 1.0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-009',
    dimension: 'SN',
    questionTextRu: 'В разговоре я склонен использовать...',
    questionTextEn: 'In conversation, I tend to use...',
    optionATextRu: 'Прямые и точные выражения',
    optionATextEn: 'Direct and precise expressions',
    optionBTextRu: 'Метафоры и аналогии',
    optionBTextEn: 'Metaphors and analogies',
    irt: { discrimination: 1.3, difficulty: 0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-010',
    dimension: 'SN',
    questionTextRu: 'Меня больше привлекает...',
    questionTextEn: 'I am more attracted to...',
    optionATextRu: 'Практичность',
    optionATextEn: 'Practicality',
    optionBTextRu: 'Оригинальность',
    optionBTextEn: 'Originality',
    irt: { discrimination: 1.7, difficulty: -0.2, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-011',
    dimension: 'SN',
    questionTextRu: 'Я склонен следовать...',
    questionTextEn: 'I tend to follow...',
    optionATextRu: 'Установленным процедурам',
    optionATextEn: 'Established procedures',
    optionBTextRu: 'Своей интуиции',
    optionBTextEn: 'My intuition',
    irt: { discrimination: 1.5, difficulty: -0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-012',
    dimension: 'SN',
    questionTextRu: 'При обучении я предпочитаю...',
    questionTextEn: 'When learning, I prefer...',
    optionATextRu: 'Пошаговые инструкции',
    optionATextEn: 'Step-by-step instructions',
    optionBTextRu: 'Общую концепцию и экспериментирование',
    optionBTextEn: 'General concept and experimentation',
    irt: { discrimination: 1.6, difficulty: 0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-013',
    dimension: 'SN',
    questionTextRu: 'Я лучше запоминаю...',
    questionTextEn: 'I remember better...',
    optionATextRu: 'Конкретные факты и детали',
    optionATextEn: 'Specific facts and details',
    optionBTextRu: 'Общие впечатления и связи',
    optionBTextEn: 'General impressions and connections',
    irt: { discrimination: 1.4, difficulty: -0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-014',
    dimension: 'SN',
    questionTextRu: 'Меня больше вдохновляет...',
    questionTextEn: 'I am more inspired by...',
    optionATextRu: 'Реальные достижения',
    optionATextEn: 'Real achievements',
    optionBTextRu: 'Новые идеи и теории',
    optionBTextEn: 'New ideas and theories',
    irt: { discrimination: 1.8, difficulty: 0.9, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-015',
    dimension: 'SN',
    questionTextRu: 'Я предпочитаю описания которые...',
    questionTextEn: 'I prefer descriptions that are...',
    optionATextRu: 'Точные и буквальные',
    optionATextEn: 'Precise and literal',
    optionBTextRu: 'Образные и символические',
    optionBTextEn: 'Figurative and symbolic',
    irt: { discrimination: 1.5, difficulty: 0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-016',
    dimension: 'SN',
    questionTextRu: 'При планировании я фокусируюсь на...',
    questionTextEn: 'When planning, I focus on...',
    optionATextRu: 'Конкретных шагах',
    optionATextEn: 'Specific steps',
    optionBTextRu: 'Общем направлении',
    optionBTextEn: 'General direction',
    irt: { discrimination: 1.7, difficulty: -0.7, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-017',
    dimension: 'SN',
    questionTextRu: 'Меня больше интересуют...',
    questionTextEn: 'I am more interested in...',
    optionATextRu: 'Практические применения',
    optionATextEn: 'Practical applications',
    optionBTextRu: 'Теоретические модели',
    optionBTextEn: 'Theoretical models',
    irt: { discrimination: 1.6, difficulty: 1.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-018',
    dimension: 'SN',
    questionTextRu: 'Я склонен...',
    questionTextEn: 'I tend to...',
    optionATextRu: 'Принимать вещи как они есть',
    optionATextEn: 'Accept things as they are',
    optionBTextRu: 'Представлять как они могли бы быть',
    optionBTextEn: 'Imagine how they could be',
    irt: { discrimination: 1.9, difficulty: 0.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-019',
    dimension: 'SN',
    questionTextRu: 'Моё внимание привлекает...',
    questionTextEn: 'My attention is drawn to...',
    optionATextRu: 'То, что происходит сейчас',
    optionATextEn: 'What is happening now',
    optionBTextRu: 'Что это может означать',
    optionBTextEn: 'What this might mean',
    irt: { discrimination: 1.4, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'SN-020',
    dimension: 'SN',
    questionTextRu: 'Я больше ценю...',
    questionTextEn: 'I value more...',
    optionATextRu: 'Здравый смысл',
    optionATextEn: 'Common sense',
    optionBTextRu: 'Креативность',
    optionBTextEn: 'Creativity',
    irt: { discrimination: 1.8, difficulty: -0.1, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
]

// ===========================================
// T/F DIMENSION (Thinking/Feeling)
// ===========================================

export const TF_ITEMS: Omit<PsychometricItem, 'id'>[] = [
  {
    itemCode: 'TF-001',
    dimension: 'TF',
    questionTextRu: 'При принятии решений я опираюсь на...',
    questionTextEn: 'When making decisions, I rely on...',
    optionATextRu: 'Логику и объективность',
    optionATextEn: 'Logic and objectivity',
    optionBTextRu: 'Ценности и чувства людей',
    optionBTextEn: 'Values and people\'s feelings',
    irt: { discrimination: 1.9, difficulty: 0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-002',
    dimension: 'TF',
    questionTextRu: 'Меня больше убеждает...',
    questionTextEn: 'I am more convinced by...',
    optionATextRu: 'Логические аргументы',
    optionATextEn: 'Logical arguments',
    optionBTextRu: 'Эмоциональная искренность',
    optionBTextEn: 'Emotional sincerity',
    irt: { discrimination: 1.7, difficulty: -0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-003',
    dimension: 'TF',
    questionTextRu: 'Я больше ценю...',
    questionTextEn: 'I value more...',
    optionATextRu: 'Справедливость',
    optionATextEn: 'Justice',
    optionBTextRu: 'Милосердие',
    optionBTextEn: 'Mercy',
    irt: { discrimination: 1.8, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-004',
    dimension: 'TF',
    questionTextRu: 'При критике я фокусируюсь на...',
    questionTextEn: 'When giving criticism, I focus on...',
    optionATextRu: 'Проблеме и её решении',
    optionATextEn: 'The problem and its solution',
    optionBTextRu: 'Чувствах человека',
    optionBTextEn: 'The person\'s feelings',
    irt: { discrimination: 1.6, difficulty: -0.6, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-005',
    dimension: 'TF',
    questionTextRu: 'Важнее быть...',
    questionTextEn: 'It is more important to be...',
    optionATextRu: 'Правым',
    optionATextEn: 'Right',
    optionBTextRu: 'Тактичным',
    optionBTextEn: 'Tactful',
    irt: { discrimination: 2.0, difficulty: 0.2, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-006',
    dimension: 'TF',
    questionTextRu: 'Я предпочитаю оценивать людей по...',
    questionTextEn: 'I prefer to judge people by...',
    optionATextRu: 'Их достижениям и компетентности',
    optionATextEn: 'Their achievements and competence',
    optionBTextRu: 'Их намерениям и усилиям',
    optionBTextEn: 'Their intentions and efforts',
    irt: { discrimination: 1.5, difficulty: 0.7, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-007',
    dimension: 'TF',
    questionTextRu: 'В конфликте я склонен...',
    questionTextEn: 'In conflict, I tend to...',
    optionATextRu: 'Анализировать ситуацию объективно',
    optionATextEn: 'Analyze the situation objectively',
    optionBTextRu: 'Учитывать чувства всех сторон',
    optionBTextEn: 'Consider everyone\'s feelings',
    irt: { discrimination: 1.6, difficulty: -0.4, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-008',
    dimension: 'TF',
    questionTextRu: 'Лучший комплимент для меня...',
    questionTextEn: 'The best compliment for me is...',
    optionATextRu: '"Вы очень умны"',
    optionATextEn: '"You are very smart"',
    optionBTextRu: '"Вы очень отзывчивы"',
    optionBTextEn: '"You are very caring"',
    irt: { discrimination: 1.4, difficulty: 0.8, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-009',
    dimension: 'TF',
    questionTextRu: 'Я склонен больше замечать...',
    questionTextEn: 'I tend to notice more...',
    optionATextRu: 'Непоследовательность в аргументах',
    optionATextEn: 'Inconsistency in arguments',
    optionBTextRu: 'Эмоциональное состояние людей',
    optionBTextEn: 'People\'s emotional state',
    irt: { discrimination: 1.7, difficulty: -0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-010',
    dimension: 'TF',
    questionTextRu: 'При решении проблем я начинаю с...',
    questionTextEn: 'When solving problems, I start with...',
    optionATextRu: 'Анализа причин',
    optionATextEn: 'Analyzing causes',
    optionBTextRu: 'Понимания влияния на людей',
    optionBTextEn: 'Understanding impact on people',
    irt: { discrimination: 1.5, difficulty: 0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-011',
    dimension: 'TF',
    questionTextRu: 'Я предпочитаю правила которые...',
    questionTextEn: 'I prefer rules that are...',
    optionATextRu: 'Чёткие и применимы ко всем',
    optionATextEn: 'Clear and apply to everyone',
    optionBTextRu: 'Гибкие с учётом обстоятельств',
    optionBTextEn: 'Flexible considering circumstances',
    irt: { discrimination: 1.6, difficulty: -0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-012',
    dimension: 'TF',
    questionTextRu: 'Меня больше мотивирует...',
    questionTextEn: 'I am more motivated by...',
    optionATextRu: 'Достижение целей и результатов',
    optionATextEn: 'Achieving goals and results',
    optionBTextRu: 'Помощь людям и гармония',
    optionBTextEn: 'Helping people and harmony',
    irt: { discrimination: 1.8, difficulty: 0.6, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-013',
    dimension: 'TF',
    questionTextRu: 'В дискуссии я больше ценю...',
    questionTextEn: 'In discussion, I value more...',
    optionATextRu: 'Ясность мышления',
    optionATextEn: 'Clarity of thinking',
    optionBTextRu: 'Гармонию отношений',
    optionBTextEn: 'Harmony of relationships',
    irt: { discrimination: 1.5, difficulty: 0.3, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-014',
    dimension: 'TF',
    questionTextRu: 'Хуже быть...',
    questionTextEn: 'It is worse to be...',
    optionATextRu: 'Несправедливым',
    optionATextEn: 'Unjust',
    optionBTextRu: 'Бесчувственным',
    optionBTextEn: 'Unfeeling',
    irt: { discrimination: 1.9, difficulty: 0.9, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-015',
    dimension: 'TF',
    questionTextRu: 'Я склонен принимать решения на основе...',
    questionTextEn: 'I tend to make decisions based on...',
    optionATextRu: 'Объективных критериев',
    optionATextEn: 'Objective criteria',
    optionBTextRu: 'Личных ценностей',
    optionBTextEn: 'Personal values',
    irt: { discrimination: 1.7, difficulty: -0.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-016',
    dimension: 'TF',
    questionTextRu: 'При обратной связи я предпочитаю...',
    questionTextEn: 'When giving feedback, I prefer to...',
    optionATextRu: 'Быть прямым и честным',
    optionATextEn: 'Be direct and honest',
    optionBTextRu: 'Быть мягким и поддерживающим',
    optionBTextEn: 'Be gentle and supportive',
    irt: { discrimination: 1.6, difficulty: -0.7, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-017',
    dimension: 'TF',
    questionTextRu: 'Я больше горжусь своей...',
    questionTextEn: 'I am more proud of my...',
    optionATextRu: 'Компетентностью',
    optionATextEn: 'Competence',
    optionBTextRu: 'Эмпатией',
    optionBTextEn: 'Empathy',
    irt: { discrimination: 1.4, difficulty: 1.0, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-018',
    dimension: 'TF',
    questionTextRu: 'В команде я больше ценю...',
    questionTextEn: 'In a team, I value more...',
    optionATextRu: 'Эффективность работы',
    optionATextEn: 'Work efficiency',
    optionBTextRu: 'Хорошие отношения',
    optionBTextEn: 'Good relationships',
    irt: { discrimination: 1.7, difficulty: 0.1, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-019',
    dimension: 'TF',
    questionTextRu: 'Я стремлюсь быть скорее...',
    questionTextEn: 'I strive to be more...',
    optionATextRu: 'Объективным',
    optionATextEn: 'Objective',
    optionBTextRu: 'Сострадательным',
    optionBTextEn: 'Compassionate',
    irt: { discrimination: 1.8, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'high',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'TF-020',
    dimension: 'TF',
    questionTextRu: 'При найме я больше ценю...',
    questionTextEn: 'When hiring, I value more...',
    optionATextRu: 'Квалификацию и опыт',
    optionATextEn: 'Qualifications and experience',
    optionBTextRu: 'Культурную совместимость',
    optionBTextEn: 'Cultural fit',
    irt: { discrimination: 1.5, difficulty: -0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
]

// ===========================================
// J/P DIMENSION (Judging/Perceiving)
// ===========================================

export const JP_ITEMS: Omit<PsychometricItem, 'id'>[] = [
  {
    itemCode: 'JP-001',
    dimension: 'JP',
    questionTextRu: 'Я предпочитаю...',
    questionTextEn: 'I prefer...',
    optionATextRu: 'Планировать заранее',
    optionATextEn: 'Planning ahead',
    optionBTextRu: 'Оставлять варианты открытыми',
    optionBTextEn: 'Keeping options open',
    irt: { discrimination: 1.8, difficulty: 0, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-002',
    dimension: 'JP',
    questionTextRu: 'Я чувствую себя лучше когда...',
    questionTextEn: 'I feel better when...',
    optionATextRu: 'Дела решены и завершены',
    optionATextEn: 'Things are settled and decided',
    optionBTextRu: 'Есть гибкость и спонтанность',
    optionBTextEn: 'There is flexibility and spontaneity',
    irt: { discrimination: 2.0, difficulty: -0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-003',
    dimension: 'JP',
    questionTextRu: 'Моё рабочее пространство обычно...',
    questionTextEn: 'My workspace is usually...',
    optionATextRu: 'Организованное и аккуратное',
    optionATextEn: 'Organized and neat',
    optionBTextRu: 'Гибкое и адаптивное',
    optionBTextEn: 'Flexible and adaptive',
    irt: { discrimination: 1.5, difficulty: -0.5, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-004',
    dimension: 'JP',
    questionTextRu: 'При работе над проектом я...',
    questionTextEn: 'When working on a project, I...',
    optionATextRu: 'Начинаю задолго до срока',
    optionATextEn: 'Start well before the deadline',
    optionBTextRu: 'Работаю лучше под давлением срока',
    optionBTextEn: 'Work better under deadline pressure',
    irt: { discrimination: 1.7, difficulty: 0.4, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-005',
    dimension: 'JP',
    questionTextRu: 'Я предпочитаю...',
    questionTextEn: 'I prefer...',
    optionATextRu: 'Структуру и порядок',
    optionATextEn: 'Structure and order',
    optionBTextRu: 'Свободу и спонтанность',
    optionBTextEn: 'Freedom and spontaneity',
    irt: { discrimination: 1.9, difficulty: 0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-006',
    dimension: 'JP',
    questionTextRu: 'При поездке я...',
    questionTextEn: 'When traveling, I...',
    optionATextRu: 'Составляю детальный план',
    optionATextEn: 'Make a detailed plan',
    optionBTextRu: 'Решаю по ходу дела',
    optionBTextEn: 'Decide as I go',
    irt: { discrimination: 1.6, difficulty: -0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-007',
    dimension: 'JP',
    questionTextRu: 'Мне больше нравится когда...',
    questionTextEn: 'I like it more when...',
    optionATextRu: 'Всё распланировано',
    optionATextEn: 'Everything is planned',
    optionBTextRu: 'Могу импровизировать',
    optionBTextEn: 'I can improvise',
    irt: { discrimination: 1.7, difficulty: 0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-008',
    dimension: 'JP',
    questionTextRu: 'Я склонен...',
    questionTextEn: 'I tend to...',
    optionATextRu: 'Принимать решения быстро',
    optionATextEn: 'Make decisions quickly',
    optionBTextRu: 'Долго взвешивать варианты',
    optionBTextEn: 'Take time weighing options',
    irt: { discrimination: 1.4, difficulty: 0.8, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-009',
    dimension: 'JP',
    questionTextRu: 'Меня больше удовлетворяет...',
    questionTextEn: 'I am more satisfied by...',
    optionATextRu: 'Завершение задачи',
    optionATextEn: 'Completing a task',
    optionBTextRu: 'Начало новой задачи',
    optionBTextEn: 'Starting a new task',
    irt: { discrimination: 1.8, difficulty: -0.2, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-010',
    dimension: 'JP',
    questionTextRu: 'При изменении планов я...',
    questionTextEn: 'When plans change, I...',
    optionATextRu: 'Чувствую дискомфорт',
    optionATextEn: 'Feel uncomfortable',
    optionBTextRu: 'Легко адаптируюсь',
    optionBTextEn: 'Adapt easily',
    irt: { discrimination: 1.6, difficulty: 0.3, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-011',
    dimension: 'JP',
    questionTextRu: 'Я предпочитаю работу которая...',
    questionTextEn: 'I prefer work that is...',
    optionATextRu: 'Структурированная с чёткими сроками',
    optionATextEn: 'Structured with clear deadlines',
    optionBTextRu: 'Гибкая без жёстких сроков',
    optionBTextEn: 'Flexible without strict deadlines',
    irt: { discrimination: 1.7, difficulty: -0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-012',
    dimension: 'JP',
    questionTextRu: 'Мой подход к задачам...',
    questionTextEn: 'My approach to tasks is...',
    optionATextRu: 'Методичный и последовательный',
    optionATextEn: 'Methodical and sequential',
    optionBTextRu: 'Гибкий и многозадачный',
    optionBTextEn: 'Flexible and multitasking',
    irt: { discrimination: 1.5, difficulty: 0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-013',
    dimension: 'JP',
    questionTextRu: 'Я лучше работаю когда...',
    questionTextEn: 'I work better when...',
    optionATextRu: 'Есть расписание',
    optionATextEn: 'There is a schedule',
    optionBTextRu: 'Могу следовать вдохновению',
    optionBTextEn: 'I can follow inspiration',
    irt: { discrimination: 1.6, difficulty: 0.7, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-014',
    dimension: 'JP',
    questionTextRu: 'При встречах я предпочитаю...',
    questionTextEn: 'For meetings, I prefer...',
    optionATextRu: 'Чёткую повестку дня',
    optionATextEn: 'A clear agenda',
    optionBTextRu: 'Свободное обсуждение',
    optionBTextEn: 'Free-flowing discussion',
    irt: { discrimination: 1.4, difficulty: -0.7, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-015',
    dimension: 'JP',
    questionTextRu: 'Дедлайны меня...',
    questionTextEn: 'Deadlines...',
    optionATextRu: 'Мотивируют начать раньше',
    optionATextEn: 'Motivate me to start early',
    optionBTextRu: 'Помогают сфокусироваться в конце',
    optionBTextEn: 'Help me focus at the end',
    irt: { discrimination: 1.8, difficulty: 0.9, guessing: 0 },
    socialDesirabilityRisk: 'medium',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-016',
    dimension: 'JP',
    questionTextRu: 'Я склонен...',
    questionTextEn: 'I tend to...',
    optionATextRu: 'Доводить дела до конца',
    optionATextEn: 'Follow through to completion',
    optionBTextRu: 'Начинать много проектов одновременно',
    optionBTextEn: 'Start many projects at once',
    irt: { discrimination: 1.7, difficulty: -0.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-017',
    dimension: 'JP',
    questionTextRu: 'Меня больше привлекает...',
    questionTextEn: 'I am more attracted to...',
    optionATextRu: 'Определённость',
    optionATextEn: 'Certainty',
    optionBTextRu: 'Открытость возможностей',
    optionBTextEn: 'Openness to possibilities',
    irt: { discrimination: 1.9, difficulty: 0.1, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-018',
    dimension: 'JP',
    questionTextRu: 'В выходные я...',
    questionTextEn: 'On weekends, I...',
    optionATextRu: 'Планирую активности заранее',
    optionATextEn: 'Plan activities in advance',
    optionBTextRu: 'Смотрю что получится',
    optionBTextEn: 'See what happens',
    irt: { discrimination: 1.5, difficulty: -0.5, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Step II',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-019',
    dimension: 'JP',
    questionTextRu: 'Я чувствую себя комфортно когда...',
    questionTextEn: 'I feel comfortable when...',
    optionATextRu: 'Всё под контролем',
    optionATextEn: 'Everything is under control',
    optionBTextRu: 'Могу быть гибким',
    optionBTextEn: 'I can be flexible',
    irt: { discrimination: 1.6, difficulty: 0.4, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'Custom',
    version: 1,
    isActive: true,
  },
  {
    itemCode: 'JP-020',
    dimension: 'JP',
    questionTextRu: 'Я предпочитаю...',
    questionTextEn: 'I prefer...',
    optionATextRu: 'Закрыть вопрос и двигаться дальше',
    optionATextEn: 'Close an issue and move on',
    optionBTextRu: 'Держать варианты открытыми подольше',
    optionBTextEn: 'Keep options open longer',
    irt: { discrimination: 2.0, difficulty: 0.6, guessing: 0 },
    socialDesirabilityRisk: 'low',
    reverseScored: false,
    source: 'MBTI Form M',
    version: 1,
    isActive: true,
  },
]

// ===========================================
// COMBINED ITEM BANK
// ===========================================

/**
 * Helper to add IDs to items
 */
function withIds<T extends Omit<PsychometricItem, 'id'>>(items: T[], prefix: string): PsychometricItem[] {
  return items.map((item, index) => ({
    ...item,
    id: `${prefix}-${(index + 1).toString().padStart(3, '0')}`
  }))
}

/**
 * Get all items for a specific dimension
 */
export function getItemsByDimension(dimension: 'EI' | 'SN' | 'TF' | 'JP'): PsychometricItem[] {
  switch (dimension) {
    case 'EI':
      return withIds(EI_ITEMS, 'EI')
    case 'SN':
      return withIds(SN_ITEMS, 'SN')
    case 'TF':
      return withIds(TF_ITEMS, 'TF')
    case 'JP':
      return withIds(JP_ITEMS, 'JP')
  }
}

/**
 * Get all items (80 total)
 */
export function getAllItems(): PsychometricItem[] {
  return [
    ...withIds(EI_ITEMS, 'EI'),
    ...withIds(SN_ITEMS, 'SN'),
    ...withIds(TF_ITEMS, 'TF'),
    ...withIds(JP_ITEMS, 'JP')
  ]
}

/**
 * Get item statistics
 */
export function getItemBankStats() {
  return {
    totalItems: 80,
    byDimension: {
      EI: EI_ITEMS.length,
      SN: SN_ITEMS.length,
      TF: TF_ITEMS.length,
      JP: JP_ITEMS.length,
    },
    avgDiscrimination: {
      EI: average(EI_ITEMS.map(i => i.irt.discrimination)),
      SN: average(SN_ITEMS.map(i => i.irt.discrimination)),
      TF: average(TF_ITEMS.map(i => i.irt.discrimination)),
      JP: average(JP_ITEMS.map(i => i.irt.discrimination)),
    },
    difficultyRange: {
      min: -1.2,
      max: 1.1,
    },
  }
}

function average(arr: number[]): number {
  return arr.reduce((sum, val) => sum + val, 0) / arr.length
}
